# Generated by Django 4.1.1 on 2022-09-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='영화 이름')),
                ('ticket_count', models.PositiveIntegerField(verbose_name='예매 수')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True, verbose_name='평점')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
